// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using P.DAL.EFCore.Context;

namespace Web.Start.Migrations
{
    [DbContext(typeof(AcademyDbContext))]
    [Migration("20200122124947_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Common.Lib.Core.Entity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Entity");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Entity");
                });

            modelBuilder.Entity("P.BL.Models.Exam", b =>
                {
                    b.HasBaseType("Common.Lib.Core.Entity");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("SubjectId");

                    b.HasDiscriminator().HasValue("Exam");
                });

            modelBuilder.Entity("P.BL.Models.Student", b =>
                {
                    b.HasBaseType("Common.Lib.Core.Entity");

                    b.Property<int>("Chair")
                        .HasColumnType("int");

                    b.Property<string>("Dni")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnName("Student_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasDiscriminator().HasValue("Student");
                });

            modelBuilder.Entity("P.BL.Models.StudentExam", b =>
                {
                    b.HasBaseType("Common.Lib.Core.Entity");

                    b.Property<Guid>("ExamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Grade")
                        .HasColumnType("float");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("StudentId");

                    b.HasDiscriminator().HasValue("StudentExam");
                });

            modelBuilder.Entity("P.BL.Models.StudentSubject", b =>
                {
                    b.HasBaseType("Common.Lib.Core.Entity");

                    b.Property<Guid>("StudentId")
                        .HasColumnName("StudentSubject_StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SubjectId")
                        .HasColumnName("StudentSubject_SubjectId")
                        .HasColumnType("uniqueidentifier");

                    b.HasDiscriminator().HasValue("StudentSubject");
                });

            modelBuilder.Entity("P.BL.Models.Subject", b =>
                {
                    b.HasBaseType("Common.Lib.Core.Entity");

                    b.Property<int>("Credits")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnName("Subject_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberStudents")
                        .HasColumnType("int");

                    b.Property<string>("Season")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("TeacherId");

                    b.HasDiscriminator().HasValue("Subject");
                });

            modelBuilder.Entity("P.BL.Models.Teacher", b =>
                {
                    b.HasBaseType("Common.Lib.Core.Entity");

                    b.Property<string>("LastName1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName2")
                        .HasColumnName("Teacher_LastName2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxCredits")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnName("Teacher_Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Teacher");
                });

            modelBuilder.Entity("P.BL.Models.Exam", b =>
                {
                    b.HasOne("P.BL.Models.Subject", null)
                        .WithMany("Exams")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("P.BL.Models.StudentExam", b =>
                {
                    b.HasOne("P.BL.Models.Student", null)
                        .WithMany("Exams")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("P.BL.Models.Subject", b =>
                {
                    b.HasOne("P.BL.Models.Teacher", null)
                        .WithMany("Subjects")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
